In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4176, 8214, 8093, 7162],
 [4176, 8214, 8093, 7148],
 [4176, 4939, 8093, 3945],
 [10, 6921, 7365, 3642, 1063],
 [10, 6921, 7365, 3642, 8937],
 [2070, 4176, 924, 8093, 3510],
 [7219, 2485, 4587, 3642]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4176 8214 8093 7162]
 [   0    0    0    0 4176 8214 8093 7148]
 [   0    0    0    0 4176 4939 8093 3945]
 [   0    0    0   10 6921 7365 3642 1063]
 [   0    0    0   10 6921 7365 3642 8937]
 [   0    0    0 2070 4176  924 8093 3510]
 [   0    0    0    0 7219 2485 4587 3642]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/sanju/Documents/DS/Generative AI/NLP/IMDB_project/myenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[ 0.01533146,  0.03795299, -0.03740451, -0.0353724 ,
         -0.01419059, -0.02461563,  0.02681908,  0.00144666,
         -0.00101642, -0.04638548],
        [ 0.01533146,  0.03795299, -0.03740451, -0.0353724 ,
         -0.01419059, -0.02461563,  0.02681908,  0.00144666,
         -0.00101642, -0.04638548],
        [ 0.01533146,  0.03795299, -0.03740451, -0.0353724 ,
         -0.01419059, -0.02461563,  0.02681908,  0.00144666,
         -0.00101642, -0.04638548],
        [ 0.01533146,  0.03795299, -0.03740451, -0.0353724 ,
         -0.01419059, -0.02461563,  0.02681908,  0.00144666,
         -0.00101642, -0.04638548],
        [ 0.04027236, -0.0225475 , -0.00781497, -0.02107455,
          0.04375248, -0.01790141,  0.0447419 ,  0.03372705,
         -0.00976808,  0.00204863],
        [ 0.03897735, -0.04998127, -0.02957302, -0.0140614 ,
         -0.03136629, -0.03584492,  0.03895107,  0.04823282,
         -0.02111862, -0.01745163],
        [ 0.01975861,  0.028815  , -0.03023647, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4176, 8214, 8093, 7162], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None